name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install needed packages
      run: sudo apt-get install netcdf-bin libnetcdf-dev libnetcdff-dev mpich libmpich-dev python3

    - name: Compile FMS library
      run: |
        cd .testing
        make deps/lib/libFMS.a -s -j

    - name: Compile symmetric
      run: |
        cd .testing
        make build/symmetric/MOM6 -s -j

    - name: Compile openMP
      run: |
        cd .testing
        make build/openmp/MOM6 -s -j

    - name: Compile asymmetric
      run: |
        cd .testing
        make build/asymmetric/MOM6 -s -j

    - name: Compile repro
      run: |
        cd .testing
        make -s -j
      env:
        TIME: ''

    - name: Test
      run: |
        cd .testing
        make test -s

    - name: Summary
      run: |
        cd .testing
        make test -s
