name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install needed packages
      run: sudo apt-get install netcdf-bin libnetcdf-dev libnetcdff-dev mpich libmpich-dev python3

    - name: Fetch submodules
      run: git submodule update --init --recursive

    - name: Compile
      run: |
        cd .testing
        make -s -j

    - name: Test
      run: |
        cd .testing
        make test -s -j
