name: Regression

on: [pull_request]

jobs:
  build-test-regression:

    runs-on: ubuntu-latest

    env:
      FCFLAGS_DEBUG: -g -O0 -Wextra -Wno-compare-reals -fbacktrace -ffpe-trap=invalid,zero,overflow -fcheck=bounds
      FCFLAGS_INIT: -finit-real=snan -finit-integer=2147483647 -finit-derived
      FCFLAGS_COVERAGE: --coverage
      MOM_TARGET_SLUG: ${GITHUB_REPOSITORY}
      MOM_TARGET_LOCAL_BRANCH: ${GITHUB_BASE_REF}
      TIME: ''


    steps:
    - name: Info
      run: env

    - name: Install needed packages
      run: sudo apt-get install netcdf-bin libnetcdf-dev libnetcdff-dev mpich libmpich-dev

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Compile FMS library
      run: |
        cd .testing
        make deps/lib/libFMS.a -s -j

    - name: Compile MOM6 in symmetric memory mode
      run: |
        cd .testing
        make build/symmetric/MOM6 -j

    - name: Create validation data
      run: |
        cd .testing
        make run.symmetric -k -s

    - name: Regression test 
      run: |
        echo $MOM_TARGET_SLUG
        echo $GITHUB_REPOSITORY
        echo $MOM_TARGET_LOCAL_BRANCH
        echo $GITHUB_REF
        cd .testing
        make test.regressions -k -s
